# Generated by Django 5.2.10 on 2026-02-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('github_link', models.URLField(blank=True)),
                ('demo_link', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('Web', 'Web Development'), ('AI', 'Artificial Intelligence'), ('App', 'Application')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
